# RMI registry endpoint
rmi.host=localhost
rmi.port=1099

# TCP game endpoint
tcp.host=localhost
tcp.port=19990

world.config=world/world.xml

# default save locations
# app.home=C:\Users\Toni\.cyberpunk-unfolds
# app.saveDirC:\Users\Toni\.cyberpunk-unfoldss/save
# app.xmlDir=C:\Users\Toni\.cyberpunk-unfolds/xml
# app.docsDir=C:\Users\Toni\.cyberpunk-unfolds/docs
